#!/bin/sh

# cisco-snmp - apt-dater plugin for Cisco ASA/IOS/PIX devices
#
# $Id$
#
# Authors:
#   Andre Ellguth <ellguth@ibh.de>
#   Thomas Liske <liske@ibh.de>
#
# Copyright Holder:
#   2009 (C) IBH IT-Service GmbH [http://www.ibh.de/apt-dater/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

case "$AD_ACTION" in
    connect)
	$AD_SSH_CMD $AD_SSH_ID $AD_SSH_OPTFLAGS -l $AD_SSH_USER -p $AD_SSH_PORT "$AD_HOSTNAME"
	;;
    install|upgrade)
	echo "'$AD_ACTION' not supported on this platform." 1>&2
	;;
    refresh)
	IMAGE='test'
	echo "ADPROTO: 0.3"
	echo "VIRT: Physical"
	echo "FORDBID: 6"
	`dirname "$0"`"/check_snmp" AD_HOSTNAME
	;;
    *)
	echo "Unhandled action '$AD_ACTION'!" 1>&2
	echo 1>&2
	set | grep ^AD_ 1>&2
	echo 1>&2
	exit 1;
	;;
esac
